# Tensors

All data in machine learning is expressed as tensors. Tensors are multi-dimensional arrays.

**Terminology**:
- **1D tensor**: vector
- **2D tensor**: matrix
- **3D+ tensor**: tensor

**Index**:
- [1. Tensor creation](#1-tensor-creation)
- [2. Tensor data types](#2-tensor-data-types)
- [3. Math with tensors](#3-math-with-tensors)

## 1. Tensor creation

In PyTorch, there are two main ways to create a tensor:
1. `torch.empty()` creates a tensor of the given size filled with uninitialized data. I.e., it allocates memory for this tensor shape, and does not initialize it with specific values

In [15]:
import torch
import math

x = torch.empty(3, 4)
print(type(x))
print("Tensor shape (rows, columns):", x.shape)
print(x)

<class 'torch.Tensor'>
Tensor shape (rows, columns): torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


2. `torch.tensor()` creates a tensor with the specific values provided

In [16]:
x = torch.tensor([[1,2], [3,4], [5, 6]])
print("Tensor shape (rows, columns):", x.shape)
print(x)

Tensor shape (rows, columns): torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


*Note: torch.tensor creates a copy of the data we specify. This is because the underlying memory representation of a python list is not the underlying memory representation of a tensor.*

## 2. Tensor data types

The simplest way to set the underlying data type of a tensor is with an optional argument at creation time.

In [23]:
from torch import bfloat16


a = torch.tensor([1,2], dtype=torch.int16)
print(x)

b = torch.tensor([3.0938,4.1875], dtype=bfloat16)
print(b)

c = b.to(torch.int32)
print(c)

tensor([1, 2], dtype=torch.int16)
tensor([3.0938, 4.1875], dtype=torch.bfloat16)
tensor([3, 4], dtype=torch.int32)


## 3. Math with tensors

So, what can we do with tensors? First, let's take a look at simple arithmetic with scalars

#### Arithmetic with tensors <> scalars

In [29]:
add = torch.zeros(2,2) + 1     # adds scalar (1) to every element in the tensor
print(add)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
multiply = torch.ones(2,2) * 3  # multiplies scalar (3) to every element in the tensor
print(multiply)

tensor([[3., 3.],
        [3., 3.]])


In [34]:
exponential = torch.tensor(([2,2],[2,2])) ** 4  # raises every element in the tensor by a scale of 4
print(exponential)

tensor([[16, 16],
        [16, 16]])


As you can see, arithmetic operations between tensors and scalars (ex. addition, subtraction, multiplication, division and exponentiation) are distributed over every element in the tensor.

#### Arithmetic with tensors <> tensors

In [ ]:
add_tensors = torch.tensor([1,2]) + torch.tensor([3,4])     # adds two 1D tensors elementwise: [1+3, 2+4] = [4, 6]
print(add_tensors)

add_tensors_v2 = torch.tensor([1,2]) + torch.tensor(([3,4], [5,6]))     # adds a 1D tensor [1,2] to each row of a 2D tensor [[3,4], [5,6]] via broadcasting
print(add_tensors_v2)

tensor([4, 6])
tensor([[4, 6],
        [6, 8]])


Adding two tensors means adding their numbers one by one in matching positions, and if their shapes allow, PyTorch will automatically stretch them to fit.